# Generated by Django 4.2.3 on 2023-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.IntegerField(null=True)),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('PreferredName', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(default='Active', max_length=100, null=True)),
                ('EmploymentStatus', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('JobLevel', models.CharField(max_length=100, null=True)),
                ('ReportingTo', models.CharField(max_length=100, null=True)),
                ('WorkEmail', models.EmailField(max_length=254)),
                ('JobInformation_Date', models.DateField(null=True)),
                ('FirstNameLastName', models.CharField(max_length=100, null=True)),
                ('SupervisorID', models.PositiveIntegerField(null=True)),
                ('Budgeter', models.CharField(max_length=100, null=True)),
                ('NetsuiteInternalID', models.IntegerField(null=True)),
                ('EmploymentStatus_Date', models.DateField(null=True)),
                ('FTE', models.CharField(max_length=100, null=True)),
                ('ResignationDate', models.DateField(null=True)),
                ('Product1', models.CharField(max_length=100, null=True)),
                ('Product2', models.CharField(max_length=100, null=True)),
                ('Entity', models.CharField(max_length=100, null=True)),
                ('HireDate', models.DateField(null=True)),
                ('Tenure', models.CharField(max_length=100, null=True)),
                ('TimeZone_Offset_Value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterimFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20)),
                ('requester_mail', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_of_days', models.IntegerField()),
                ('reason', models.CharField(choices=[('Business Travel', 'Business Travel'), ('Office Closure', 'Office Closure'), ('Others', 'Others')], default='Others', max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('tenure', models.IntegerField(null=True)),
                ('submission_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Approved', 'True'), ('Rejected', 'False')], default='Approved', max_length=50, null=True)),
            ],
        ),
    ]
